// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8zoZxzv4ddMlMHXtv7o4Xt_MVyxwuEUQ',
    appId: '1:646225790950:web:76e2e809459696ac083827',
    messagingSenderId: '646225790950',
    projectId: 'mediscan-5b8e2',
    authDomain: 'mediscan-5b8e2.firebaseapp.com',
    storageBucket: 'mediscan-5b8e2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxxj0pi4b0TNnb59qN5RmcPdKgxb312SY',
    appId: '1:646225790950:android:e45c76f3702c18de083827',
    messagingSenderId: '646225790950',
    projectId: 'mediscan-5b8e2',
    storageBucket: 'mediscan-5b8e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiuNceGST4-pbYUKVf_CJAg4QhGm-fu7A',
    appId: '1:646225790950:ios:d6140935a22234f8083827',
    messagingSenderId: '646225790950',
    projectId: 'mediscan-5b8e2',
    storageBucket: 'mediscan-5b8e2.firebasestorage.app',
    iosBundleId: 'com.example.mediscan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiuNceGST4-pbYUKVf_CJAg4QhGm-fu7A',
    appId: '1:646225790950:ios:d6140935a22234f8083827',
    messagingSenderId: '646225790950',
    projectId: 'mediscan-5b8e2',
    storageBucket: 'mediscan-5b8e2.firebasestorage.app',
    iosBundleId: 'com.example.mediscan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8zoZxzv4ddMlMHXtv7o4Xt_MVyxwuEUQ',
    appId: '1:646225790950:web:c2ed1620ad4c53bc083827',
    messagingSenderId: '646225790950',
    projectId: 'mediscan-5b8e2',
    authDomain: 'mediscan-5b8e2.firebaseapp.com',
    storageBucket: 'mediscan-5b8e2.firebasestorage.app',
  );
}
